### ISSUE TITLE
廣韻正字問題 Issue of Guangyun's Variants

### ISSUE THREAD

**Issue by mkpoli** [nk2028/yitizi#10]
Guangyun has some historical variant as orthodox character (正字) which are not included as of f3851be60463be66fd13d060c3e5be658a0aff17 (v0.1.1)

Modern Common Variant | Guangyun Variant
------------------------------|----------------------
樣 | 㨾
姊 | 𡛷

For archiving, characters that are already supported:

Modern Common Variant | Guangyun Variant
------------------------------|----------------------
侯 | 𠋫
魂 | 䰟
島 | 㠀

These are incomplete lists and should be updated.

**Comment by syimyuzya** [comment]
由於 Qieyun.js 已換用 poem 的資料，上述「姊」「侯」「島」三字之異體雖然並未收錄，但廣韻資料之字頭已經變更為常用碼位。「魂䰟」目前 Yitizi.js 亦已收為異體。

於是一開始列的這些異體，只有「樣」仍未收錄。

不過此外還有一些近期發現的：

- 「韓」「𩏑」（《廣韻》並無「韓」字頭，收入該字頭的電子資料均有誤）
- 「脈」「𧖴」（同上）
- 「皓」「晧」（有趣的是《廣韻》韻目和字頭均寫「晧」而正文兩形均有）
  - 另外韻典異體表中有個莫名的「皓顥皝」三字互為異體，其中「顥皓」問題不大，但「皝」則由來不明

**Comment by syimyuzya** [comment]
Resolved in v0.1.2 :smiley:
