### ISSUE TITLE
Entries with no variants in `yitizi.csv`

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/yitizi#5]
丁、丈、不、且……這些個字列在 `yitizi.csv` 中但是完全沒有與之關聯的異體。

想知道為什麼這些字會留在表中（比如也許是為了明確表明它們沒有異體？）

**Comment by syimyuzya** [comment]
另外，表末尾還有若干這樣的 CJK 兼容區的字，意味不明(?)

**Comment by ayaka14732** [comment]
是的，是為了明確表明它們沒有異體～這些字在生成 `yitizi.json` 之後就沒有了。

CJK 兼容區的字確實是不應該出現的，應該視為異體字。
